# Generated by Django 5.1 on 2025-01-30 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0002_session_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='title',
        ),
    ]
