# Generated by Django 5.1 on 2025-01-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0005_alter_session_end_time_alter_session_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
    ]
