# Generated by Django 5.1 on 2025-01-31 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0007_sessionparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 4, 26, 33, 458138, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
