# Generated by Django 5.1 on 2025-01-31 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0008_sessionparticipant_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
