# Generated by Django 5.1 on 2025-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0009_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
