# Generated by Django 5.1 on 2025-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0010_alter_session_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='accpet_participants',
            field=models.BooleanField(default=True),
        ),
    ]
