# Generated by Django 5.1 on 2025-02-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yoga_sessions', '0011_session_accpet_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='accpet_participants',
            new_name='accept_participants',
        ),
    ]
